workflows:
  ios-workflow:
    name: iOS App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        SCHEME: "InvoicerApp"
        CONFIGURATION: "Debug"        # arba "Release"
    cache:
      cache_paths:
        - ~/.cache/Homebrew
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
        - ~/Library/Developer/XCPGDevices
        - ~/Library/Developer/Xcode/Products
    scripts:
      - name: Print Xcode version & list files
        script: |
          xcodebuild -version
          pwd
          ls -la

      - name: (Optional) Generate .xcodeproj with XcodeGen if project.yml exists
        script: |
          if [ -f project.yml ]; then
            brew install xcodegen || true
            xcodegen generate
          else
            echo "No project.yml; using existing .xcodeproj"
          fi

      - name: Clean build (no code signing)
        script: |
          set -euo pipefail
          # Jei turi workspace vietoj xcodeproj, pakeisk -project į -workspace ir pridėk -scheme atitinkamai.
          xcodebuild \
            -project InvoicerApp.xcodeproj \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            clean build | xcpretty

      - name: Collect .app artifact
        script: |
          set -euo pipefail
          # Rask su-built'intą .app:
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -path "*/Build/Products/$CONFIGURATION-iphoneos/${SCHEME}.app" -print -quit)
          if [ -z "${APP_PATH:-}" ]; then
            echo "Could not find .app in DerivedData. Dumping possible paths:"
            find ~/Library/Developer/Xcode/DerivedData -type d -name "${SCHEME}.app" | sed 's#^# -> #'
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          mkdir -p "$CM_ARTIFACTS"
          cp -R "$APP_PATH" "$CM_ARTIFACTS/"

    artifacts:
      - $CM_ARTIFACTS/*.app
    publishing:
      email:
        recipients:
          - your@email.here
        notify:
          success: true
          failure: true
