workflows:
  # Esamas workflow paliktas kaip buvo (build'ina device .app)
  ios-workflow:
    name: iOS App (Debug .app)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        SCHEME: "InvoicerApp"
        CONFIGURATION: "Debug"
    cache:
      cache_paths:
        - ~/.cache/Homebrew
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Show Xcode version & repo layout
        script: |
          set -e
          xcodebuild -version
          echo "--- repo root ---"; pwd; ls -la
          echo "--- InvoicerApp dir ---"; ls -la InvoicerApp || true

      - name: Generate .xcodeproj with XcodeGen
        script: |
          set -e
          brew install xcodegen || true
          xcodegen generate
          ls -la *.xcodeproj

      - name: Clean & build (no code signing)
        script: |
          set -eo pipefail
          xcodebuild \
            -project InvoicerApp.xcodeproj \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            clean build | xcpretty

      - name: Collect .app artifact
        script: |
          set -eo pipefail
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -path "*/Build/Products/$CONFIGURATION-iphoneos/${SCHEME}.app" -print -quit)
          echo "Found app at: $APP_PATH"
          ART_DIR="${CM_ARTIFACTS:-$PWD/artifacts}"
          mkdir -p "$ART_DIR"
          cp -R "$APP_PATH" "$ART_DIR/"

    artifacts:
      - artifacts/*.app

  # NAUJAS: iOS SIMULIATORIAUS build'as App Preview (Stellar) naršyklėje
  ios-simulator-preview:
    name: iOS Simulator (App Preview)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        SCHEME: "InvoicerApp"
        CONFIGURATION: "Debug"
    cache:
      cache_paths:
        - ~/.cache/Homebrew
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Show Xcode version & repo layout
        script: |
          set -e
          xcodebuild -version
          echo "--- repo root ---"; pwd; ls -la
          echo "--- InvoicerApp dir ---"; ls -la InvoicerApp || true

      - name: Generate .xcodeproj with XcodeGen
        script: |
          set -e
          brew install xcodegen || true
          xcodegen generate
          ls -la *.xcodeproj

      - name: Build for iOS Simulator (.app for App Preview)
        script: |
          set -eo pipefail
          # svarbu: -sdk iphonesimulator ir 'generic/platform=iOS Simulator'
          xcodebuild \
            -project InvoicerApp.xcodeproj \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            clean build | xcpretty

    # App Preview „Quick Launch“ atsiras, kai artefaktuose yra SIMULIATORIAUS .app
    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
