workflows:
  ios-workflow:
    name: iOS App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        SCHEME: "InvoicerApp"
        CONFIGURATION: "Debug"                   # arba "Release"
    cache:
      cache_paths:
        - ~/.cache/Homebrew
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Show Xcode version & repo layout
        script: |
          set -e
          xcodebuild -version
          echo "--- repo root ---"
          pwd
          ls -la
          echo "--- InvoicerApp dir ---"
          ls -la InvoicerApp || true

      - name: Generate .xcodeproj with XcodeGen
        script: |
          set -e
          brew install xcodegen || true
          xcodegen generate
          echo "Generated Xcode project:"
          ls -la *.xcodeproj

      - name: Clean & build (no code signing)
        script: |
          set -eo pipefail
          xcodebuild \
            -project InvoicerApp.xcodeproj \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            clean build | xcpretty

      - name: Collect .app artifact
        script: |
          set -eo pipefail
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -path "*/Build/Products/$CONFIGURATION-iphoneos/${SCHEME}.app" -print -quit)
          if [ -z "${APP_PATH:-}" ]; then
            echo "Could not find .app in DerivedData. Listing candidates:"
            find ~/Library/Developer/Xcode/DerivedData -type d -name "${SCHEME}.app" | sed 's#^# -> #'
            exit 1
          fi
          echo "Found app at: $APP_PATH"

          # Naudokime lokalinį artefaktų katalogą, jei CM_ARTIFACTS nėra nustatytas
          ART_DIR="${CM_ARTIFACTS:-$PWD/artifacts}"
          mkdir -p "$ART_DIR"
          cp -R "$APP_PATH" "$ART_DIR/"

    artifacts:
      - artifacts/*.app
