name: InvoicerApp

options:
  bundleIdPrefix: lt.vdxas

configs:
  Debug: debug
  Release: release

settings:
  BASE_SDK: iphoneos
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  SWIFT_VERSION: "5.0"

targets:
  InvoicerApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    # Įtraukiame tik vieną failą su @main, kad nebūtų "main attribute can only apply to one type"
    sources:
      - path: InvoicerApp/InvoicerApp.swift
    info:
      path: InvoicerApp/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: lt.vdxas.invoicerwrapper
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: "1"        # iPhone
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
